"""
Enterprise Rare Blood Type Availability Analytics
Pipeline Stage 9 — Inventory Transaction Engine (v2 upgrade)
=====================================================

This is the core of the project upgrade: it replaces "trust the static
snapshot" with "recompute current inventory from the transaction ledger",
per the reconciliation equation:

    Current Inventory
        =
    Opening Inventory (0)
        + DONATION
        + TRANSFER_IN
        - ISSUE
        - TRANSFER_OUT
        - EXPIRY
        + ADJUSTMENT

It reads the transaction ledger generated by
data_generation/02_generate_transactional_data.py (itself tied to real
donation history -- see that script's docstring), and produces:

    gold/gold_inventory_state          component-level current state,
                                        coverage days, shortage score,
                                        priority level, recommended action
    gold/gold_demand_analytics         daily/average demand per
                                        bank+blood_group+component
    gold/gold_transfer_history         cleaned, validated transfer ledger

All business-rule values (component types, shelf life, scoring weights,
priority bands, recommended actions) are loaded from config/*.yaml -- this
script contains NO hard-coded copies of those numbers.
"""

from __future__ import annotations

import sys
from pathlib import Path

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    DateType,
    DoubleType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from config.config_loader import get_project_config, get_thresholds  # noqa: E402

# ============================================================================
# CONFIGURATION (loaded from config/*.yaml -- single source of truth)
# ============================================================================

APP_NAME = "Enterprise Rare Blood Analytics - Inventory Transaction Engine"

RAW_DIR = PROJECT_ROOT / "data" / "raw"
SILVER_DIR = PROJECT_ROOT / "data" / "silver"
GOLD_DIR = PROJECT_ROOT / "data" / "gold"

TRANSACTIONS_PATH = RAW_DIR / "inventory_transactions.csv"
TRANSFERS_PATH = RAW_DIR / "blood_transfers.csv"
ISSUES_PATH = RAW_DIR / "blood_issues.csv"

GOLD_INVENTORY_STATE = GOLD_DIR / "gold_inventory_state"
GOLD_DEMAND_ANALYTICS = GOLD_DIR / "gold_demand_analytics"
GOLD_TRANSFER_HISTORY = GOLD_DIR / "gold_transfer_history"

_project_cfg = get_project_config()
_thresholds_cfg = get_thresholds()

VALID_BLOOD_GROUPS = _project_cfg["blood_groups"]["valid"]
RARE_BLOOD_GROUPS = _project_cfg["blood_groups"]["rare"]
COMPONENT_TYPES = _project_cfg["component_types"]["valid"]
SHELF_LIFE_DAYS = _project_cfg["component_types"]["shelf_life_days"]

MINIMUM_DEMAND_FLOOR = _thresholds_cfg["coverage"]["minimum_demand_floor"]

SCORING_WEIGHTS = _thresholds_cfg["shortage_scoring"]["weights"]
COVERAGE_CRITICAL_BELOW = _thresholds_cfg["shortage_scoring"]["coverage_days_critical_below"]
COVERAGE_LOW_BELOW = _thresholds_cfg["shortage_scoring"]["coverage_days_low_below"]
COVERAGE_HEALTHY_ABOVE = _thresholds_cfg["shortage_scoring"]["coverage_days_healthy_above"]

PRIORITY_BANDS = _thresholds_cfg["shortage_scoring"]["bands"]
RECOMMENDED_ACTIONS = _thresholds_cfg["recommended_actions"]


# ============================================================================
# SPARK SESSION
# ============================================================================

def create_spark_session() -> SparkSession:
    spark = (
        SparkSession.builder.appName(APP_NAME)
        .master("local[*]")
        .config("spark.sql.session.timeZone", "UTC")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("ERROR")
    return spark


# ============================================================================
# READ TRANSACTION LEDGER
# ============================================================================

TRANSACTION_SCHEMA = StructType([
    StructField("transaction_id", StringType(), True),
    StructField("blood_bank_id", StringType(), True),
    StructField("blood_group", StringType(), True),
    StructField("component_type", StringType(), True),
    StructField("transaction_type", StringType(), True),
    StructField("units", DoubleType(), True),
    StructField("transaction_timestamp", TimestampType(), True),
    StructField("source_donation_id", StringType(), True),
    StructField("source_transfer_id", StringType(), True),
    StructField("destination_bank_id", StringType(), True),
    StructField("status", StringType(), True),
    StructField("issue_id", StringType(), True),
])


def read_transactions(spark: SparkSession) -> DataFrame:
    if not TRANSACTIONS_PATH.exists():
        raise FileNotFoundError(
            f"Transaction ledger not found at {TRANSACTIONS_PATH}. "
            f"Run data_generation/02_generate_transactional_data.py first."
        )
    return (
        spark.read.option("header", "true")
        .schema(TRANSACTION_SCHEMA)
        .csv(str(TRANSACTIONS_PATH))
    )


# ============================================================================
# STEP 1 — RECOMPUTE CURRENT INVENTORY FROM THE LEDGER (not trusted snapshot)
# ============================================================================

def compute_inventory_balances(transactions: DataFrame) -> DataFrame:
    """The reconciliation step: current balance = signed sum of every
    transaction for that (bank, blood_group, component_type) key.
    DONATION / TRANSFER_IN / ADJUSTMENT are inflows; ISSUE / TRANSFER_OUT /
    EXPIRY are outflows (ADJUSTMENT can itself carry a negative `units`
    value for a downward correction, so it is always added, never negated).
    """
    signed = transactions.withColumn(
        "signed_units",
        F.when(F.col("transaction_type").isin("DONATION", "TRANSFER_IN", "ADJUSTMENT"), F.col("units"))
        .otherwise(-F.col("units")),
    )

    balances = signed.groupBy("blood_bank_id", "blood_group", "component_type").agg(
        F.sum("signed_units").alias("available_units"),
        F.max("transaction_timestamp").alias("last_updated"),
        F.max(F.when(F.col("transaction_type") == "DONATION", F.col("transaction_timestamp"))).alias(
            "last_donation_at"
        ),
        F.sum(F.when(F.col("transaction_type") == "EXPIRY", F.col("units")).otherwise(0)).alias(
            "lifetime_expired_units"
        ),
    )

    balances = balances.withColumn("available_units", F.round(F.col("available_units")).cast("int"))
    return balances


def compute_expiry_status(balances: DataFrame) -> DataFrame:
    """Classify each key's freshness based on the shelf life of its
    component type and the most recent donation feeding it."""
    shelf_life_expr = F.create_map(
        [F.lit(x) for pair in SHELF_LIFE_DAYS.items() for x in pair]
    )[F.col("component_type")]

    days_since_donation = F.datediff(F.current_date(), F.to_date("last_donation_at"))
    days_left = shelf_life_expr - days_since_donation

    expiry_soon_days = _thresholds_cfg["expiry"]["expiring_soon_days"]

    return balances.withColumn(
        "expiry_status",
        F.when(F.col("last_donation_at").isNull(), F.lit("VALID"))
        .when(days_left <= 0, F.lit("EXPIRED"))
        .when(days_left <= expiry_soon_days, F.lit("EXPIRING_SOON"))
        .otherwise(F.lit("VALID")),
    )


# ============================================================================
# STEP 2 — DEMAND ANALYTICS
# ============================================================================

def compute_demand_analytics(transactions: DataFrame) -> DataFrame:
    """Daily/weekly/monthly demand per (bank, blood_group, component_type),
    computed from ISSUE transactions only. average_daily_demand divides
    total issued units by the GLOBAL observation window (shared across all
    keys) so that a key with zero issues correctly gets average_daily_demand
    = 0 rather than an undefined value, and demand figures are comparable
    across keys."""
    issues = transactions.filter(F.col("transaction_type") == "ISSUE")

    window_bounds = issues.agg(
        F.min("transaction_timestamp").alias("window_start"),
        F.max("transaction_timestamp").alias("window_end"),
    ).collect()[0]

    if window_bounds["window_start"] is None:
        window_days = 1
    else:
        window_days = max(
            1, (window_bounds["window_end"] - window_bounds["window_start"]).days + 1
        )

    demand = issues.groupBy("blood_bank_id", "blood_group", "component_type").agg(
        F.sum("units").alias("total_units_issued"),
        F.count("transaction_id").alias("issue_event_count"),
    )

    demand = demand.withColumn("observation_window_days", F.lit(window_days))
    demand = demand.withColumn(
        "average_daily_demand",
        F.round(F.col("total_units_issued") / F.lit(window_days), 3),
    )
    demand = demand.withColumn(
        "average_weekly_demand", F.round(F.col("average_daily_demand") * 7, 2)
    )
    demand = demand.withColumn(
        "average_monthly_demand", F.round(F.col("average_daily_demand") * 30, 2)
    )

    return demand


# ============================================================================
# STEP 3 — COVERAGE DAYS
# ============================================================================

def add_coverage_days(inventory: DataFrame, demand: DataFrame) -> DataFrame:
    """coverage_days = available_units / average_daily_demand.

    A key with average_daily_demand == 0 (no recorded consumption) does NOT
    get literal infinite coverage -- that would be misleading. Instead it is
    flagged has_demand_data = false and coverage_days is left null; the
    dashboard/reporting layer should treat "no demand data" as its own
    category rather than "infinitely safe".
    """
    joined = inventory.join(
        demand.select("blood_bank_id", "blood_group", "component_type", "average_daily_demand",
                       "average_weekly_demand", "average_monthly_demand"),
        on=["blood_bank_id", "blood_group", "component_type"],
        how="left",
    )
    joined = joined.withColumn("average_daily_demand", F.coalesce(F.col("average_daily_demand"), F.lit(0.0)))
    joined = joined.withColumn("has_demand_data", F.col("average_daily_demand") > 0)

    joined = joined.withColumn(
        "coverage_days",
        F.when(
            F.col("has_demand_data"),
            F.round(F.col("available_units") / F.greatest(F.col("average_daily_demand"), F.lit(MINIMUM_DEMAND_FLOOR)), 1),
        ),
    )
    return joined


# ============================================================================
# STEP 4 — SHORTAGE SCORING (transparent, rule-based, 0-100)
# ============================================================================

def _inventory_level_sub_score() -> F.Column:
    """0-100, higher units -> lower urgency. Piecewise on available_units."""
    units = F.col("available_units")
    return (
        F.when(units == 0, F.lit(100))
        .when(units <= 5, F.lit(90))
        .when(units <= 10, F.lit(60))
        .when(units <= 20, F.lit(30))
        .otherwise(F.lit(10))
    )


def _coverage_sub_score() -> F.Column:
    """0-100, fewer coverage days -> higher urgency. No demand data is
    treated as a neutral middle score (unknown risk), not "safe"."""
    coverage = F.col("coverage_days")
    return (
        F.when(~F.col("has_demand_data"), F.lit(50))
        .when(coverage < COVERAGE_CRITICAL_BELOW, F.lit(100))
        .when(coverage < COVERAGE_LOW_BELOW, F.lit(70))
        .when(coverage < COVERAGE_HEALTHY_ABOVE, F.lit(35))
        .otherwise(F.lit(10))
    )


def _expiry_sub_score() -> F.Column:
    return (
        F.when(F.col("expiry_status") == "EXPIRED", F.lit(100))
        .when(F.col("expiry_status") == "EXPIRING_SOON", F.lit(60))
        .otherwise(F.lit(0))
    )


def add_donation_trend_sub_score(inventory: DataFrame, transactions: DataFrame) -> DataFrame:
    """Compares donation inflow in the most recent 30 days of the ledger's
    own timeline against the prior 30 days. A falling or absent recent
    donation rate raises urgency; the reference point is the latest
    transaction timestamp in the ledger (not wall-clock "today"), since this
    is synthetic historical data, not a live feed."""
    latest_ts = transactions.agg(F.max("transaction_timestamp").alias("latest")).collect()[0]["latest"]

    donations = transactions.filter(F.col("transaction_type") == "DONATION")
    recent = donations.filter(F.col("transaction_timestamp") >= F.lit(latest_ts) - F.expr("INTERVAL 30 days"))
    prior = donations.filter(
        (F.col("transaction_timestamp") < F.lit(latest_ts) - F.expr("INTERVAL 30 days"))
        & (F.col("transaction_timestamp") >= F.lit(latest_ts) - F.expr("INTERVAL 60 days"))
    )

    recent_agg = recent.groupBy("blood_bank_id", "blood_group", "component_type").agg(
        F.sum("units").alias("recent_donation_units")
    )
    prior_agg = prior.groupBy("blood_bank_id", "blood_group", "component_type").agg(
        F.sum("units").alias("prior_donation_units")
    )

    trend = inventory.join(recent_agg, on=["blood_bank_id", "blood_group", "component_type"], how="left")
    trend = trend.join(prior_agg, on=["blood_bank_id", "blood_group", "component_type"], how="left")
    trend = trend.withColumn("recent_donation_units", F.coalesce(F.col("recent_donation_units"), F.lit(0.0)))
    trend = trend.withColumn("prior_donation_units", F.coalesce(F.col("prior_donation_units"), F.lit(0.0)))

    trend = trend.withColumn(
        "donation_trend_sub_score",
        F.when(F.col("recent_donation_units") == 0, F.lit(100))
        .when(F.col("prior_donation_units") == 0, F.lit(50))  # no prior baseline -> neutral
        .when(F.col("recent_donation_units") / F.col("prior_donation_units") >= 1.0, F.lit(0))
        .when(F.col("recent_donation_units") / F.col("prior_donation_units") >= 0.5, F.lit(30))
        .otherwise(F.lit(70)),
    )
    return trend


def add_shortage_score(inventory: DataFrame) -> DataFrame:
    """shortage_score = weighted sum of 4 sub-scores (each 0-100), rounded
    and clipped to [0, 100]. Weights come from config/thresholds.yaml and
    sum to 1.0 -- see that file for the documented rationale."""
    inventory = inventory.withColumn("inventory_level_sub_score", _inventory_level_sub_score())
    inventory = inventory.withColumn("coverage_sub_score", _coverage_sub_score())
    inventory = inventory.withColumn("expiry_sub_score", _expiry_sub_score())

    raw_score = (
        F.col("inventory_level_sub_score") * F.lit(SCORING_WEIGHTS["inventory_level"])
        + F.col("coverage_sub_score") * F.lit(SCORING_WEIGHTS["coverage_days"])
        + F.col("expiry_sub_score") * F.lit(SCORING_WEIGHTS["expiry_risk"])
        + F.col("donation_trend_sub_score") * F.lit(SCORING_WEIGHTS["donation_trend"])
    )
    inventory = inventory.withColumn(
        "shortage_score", F.greatest(F.least(F.round(raw_score).cast("int"), F.lit(100)), F.lit(0))
    )
    return inventory


def add_priority_level(inventory: DataFrame) -> DataFrame:
    score = F.col("shortage_score")
    inventory = inventory.withColumn(
        "priority_level",
        F.when(score <= PRIORITY_BANDS["healthy_max"], F.lit("HEALTHY"))
        .when(score <= PRIORITY_BANDS["monitor_max"], F.lit("MONITOR"))
        .when(score <= PRIORITY_BANDS["low_max"], F.lit("LOW"))
        .when(score <= PRIORITY_BANDS["critical_max"], F.lit("CRITICAL"))
        .otherwise(F.lit("EMERGENCY")),
    )

    action_map = F.create_map([F.lit(x) for pair in RECOMMENDED_ACTIONS.items() for x in pair])
    inventory = inventory.withColumn("recommended_action", action_map[F.col("priority_level")])
    return inventory


# ============================================================================
# TRANSFER HISTORY (cleaned + validated)
# ============================================================================

def read_and_validate_transfers(spark: SparkSession, blood_bank_ids: set) -> DataFrame:
    if not TRANSFERS_PATH.exists():
        return spark.createDataFrame([], schema=StructType([
            StructField("transfer_id", StringType(), True),
            StructField("source_bank_id", StringType(), True),
            StructField("destination_bank_id", StringType(), True),
            StructField("blood_group", StringType(), True),
            StructField("component_type", StringType(), True),
            StructField("units", DoubleType(), True),
            StructField("transfer_date", DateType(), True),
            StructField("status", StringType(), True),
        ]))

    transfers = spark.read.option("header", "true").option("inferSchema", "true").csv(str(TRANSFERS_PATH))

    # Data quality validation (Section 15 of the upgrade brief): positive
    # units, source != destination, both banks must be real.
    transfers = transfers.withColumn(
        "is_valid",
        (F.col("units") > 0)
        & (F.col("source_bank_id") != F.col("destination_bank_id"))
        & F.col("source_bank_id").isin(list(blood_bank_ids))
        & F.col("destination_bank_id").isin(list(blood_bank_ids)),
    )
    return transfers


# ============================================================================
# WRITE + VALIDATE
# ============================================================================

def write_gold(df: DataFrame, path: Path, label: str) -> None:
    df.coalesce(1).write.mode("overwrite").parquet(str(path))
    print(f"  {label} -> {path}")


def run_reconciliation_check(transactions: DataFrame, inventory_state: DataFrame) -> bool:
    """Independently re-verifies (inside Spark, not trusting the generator's
    own self-check) that summing every transaction per key reproduces the
    exact closing balance in gold_inventory_state. This is the automated
    equivalent of the reconciliation equation required by the upgrade
    brief section 31."""
    recomputed = compute_inventory_balances(transactions).select(
        "blood_bank_id", "blood_group", "component_type",
        F.col("available_units").alias("recomputed_units"),
    )
    compare = inventory_state.select(
        "blood_bank_id", "blood_group", "component_type", "available_units"
    ).join(recomputed, on=["blood_bank_id", "blood_group", "component_type"], how="inner")

    mismatches = compare.filter(F.col("available_units") != F.col("recomputed_units")).count()
    negative = inventory_state.filter(F.col("available_units") < 0).count()

    print(f"\nReconciliation check: {mismatches} mismatched ledgers (must be 0)")
    print(f"Negative-balance check: {negative} ledgers below zero (must be 0)")
    return mismatches == 0 and negative == 0


# ============================================================================
# MAIN
# ============================================================================

def main() -> None:
    print("=" * 45)
    print("INVENTORY TRANSACTION ENGINE (v2 upgrade)")
    print("=" * 45)

    spark = create_spark_session()

    try:
        print("\nReading transaction ledger...")
        transactions = read_transactions(spark)
        txn_count = transactions.count()
        print(f"Transactions loaded: {txn_count}")

        if txn_count == 0:
            print("ERROR: transaction ledger is empty. "
                  "Run data_generation/02_generate_transactional_data.py first.")
            sys.exit(1)

        print("\nStep 1: Recomputing current inventory balances from the ledger...")
        balances = compute_inventory_balances(transactions)
        balances = compute_expiry_status(balances)

        print("Step 2: Computing demand analytics...")
        demand = compute_demand_analytics(transactions)

        print("Step 3: Computing coverage days...")
        inventory = add_coverage_days(balances, demand)

        print("Step 4: Computing donation trend sub-score...")
        inventory = add_donation_trend_sub_score(inventory, transactions)

        print("Step 5: Computing shortage score + priority level...")
        inventory = add_shortage_score(inventory)
        inventory = add_priority_level(inventory)

        blood_bank_ids = {
            r["blood_bank_id"] for r in inventory.select("blood_bank_id").distinct().collect()
        }
        print("\nReading and validating blood transfers...")
        transfers = read_and_validate_transfers(spark, blood_bank_ids)
        invalid_transfers = transfers.filter(~F.col("is_valid")).count() if transfers.count() > 0 else 0
        print(f"Transfer records: {transfers.count()} ({invalid_transfers} flagged invalid)")

        reconciliation_ok = run_reconciliation_check(transactions, inventory)

        gold_inventory_state = inventory.select(
            "blood_bank_id", "blood_group", "component_type", "available_units",
            "expiry_status", "lifetime_expired_units", "has_demand_data",
            "average_daily_demand", "average_weekly_demand", "average_monthly_demand",
            "coverage_days", "inventory_level_sub_score", "coverage_sub_score",
            "expiry_sub_score", "donation_trend_sub_score", "shortage_score",
            "priority_level", "recommended_action", "last_updated",
        )

        gold_demand_analytics = demand.select(
            "blood_bank_id", "blood_group", "component_type", "total_units_issued",
            "issue_event_count", "observation_window_days", "average_daily_demand",
            "average_weekly_demand", "average_monthly_demand",
        )

        print("\nWriting Gold datasets...")
        write_gold(gold_inventory_state, GOLD_INVENTORY_STATE, "gold_inventory_state")
        write_gold(gold_demand_analytics, GOLD_DEMAND_ANALYTICS, "gold_demand_analytics")
        write_gold(transfers, GOLD_TRANSFER_HISTORY, "gold_transfer_history")

        print("\n" + "=" * 45)
        print("SUMMARY")
        print("=" * 45)
        priority_counts = gold_inventory_state.groupBy("priority_level").count().collect()
        for row in sorted(priority_counts, key=lambda r: r["priority_level"]):
            print(f"  {row['priority_level']:<10}: {row['count']}")

        rare_state = gold_inventory_state.filter(F.col("blood_group").isin(RARE_BLOOD_GROUPS))
        print(f"\nRare blood group ledgers: {rare_state.count()}")
        print(f"Rare blood EMERGENCY/CRITICAL count: "
              f"{rare_state.filter(F.col('priority_level').isin('EMERGENCY', 'CRITICAL')).count()}")

        print("\n" + "=" * 45)
        if reconciliation_ok:
            print("INVENTORY TRANSACTION ENGINE COMPLETE — RECONCILIATION PASSED")
        else:
            print("INVENTORY TRANSACTION ENGINE COMPLETE — RECONCILIATION FAILED")
        print("=" * 45)

        if not reconciliation_ok:
            sys.exit(1)

    except FileNotFoundError as exc:
        print(f"\nERROR: {exc}")
        sys.exit(1)

    finally:
        spark.stop()


if __name__ == "__main__":
    main()
